[package]
name = "train_piano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.9.1"
rand = "0.8.5"
sdl2 = { version = "0.36", default-features = false, features = ["gfx"] }
